# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aliyun = {
      source = "aliyun/alicloud"
      version = "~> 1.186.0"
    }
    random = {
      source = "hashicorp/random"
      version = "~> 3.4.3"
    }
  }
}

provider "alicloud" {
  region = "cn-shanghai"
}
